image: python:3.13-slim

variables:
  DS_ENFORCE_NEW_ANALYZER: 'true'
  DS_ENABLE_VULNERABILITY_SCAN: 'true'
  DS_PIP_MANIFEST_FILE_NAME_PATTERN: 'requirements.txt'
  GITLAB_ADVANCED_SAST_ENABLED: 'true'
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

include:
  - template: Jobs/SAST.gitlab-ci.yml
  - template: Jobs/Secret-Detection.gitlab-ci.yml
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml

sast:
  stage: test
  artifacts:
    name: sast
    paths:
      - gl-sast-report.json
    reports:
      sast: gl-sast-report.json
    when: always

secret_detection:
  stage: test
